/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {type Demo} from 'a2ui-bridge';
import demos from './demos.json';

/**
 * The demos every sample renderer serves on the demo wall: the four showcase demos
 * in this directory, followed by the A2UI basic-catalog examples from the pinned
 * `@a2ui/web_core` package. `demos.json` is generated by `yarn generate:demos`.
 *
 * JSON imports are typed loosely (a `version` is a `string`, not `'v0.9'`), so the
 * generator's validation is what guarantees these match `Demo`.
 */
export const DEMOS = demos as unknown as Demo[];
