/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * A discrete skill, tool, or capability exposed by an A2A Agent.
 */
export interface AgentSkill {
  /** Unique skill identifier. */
  id: string;
  /** Human-readable skill name. */
  name: string;
  /** Description of what this skill does. */
  description?: string;
  /** Specific input modalities accepted by this skill (e.g. 'text', 'audio', 'image'). */
  inputModes?: string[];
  /** Specific output modalities produced by this skill (e.g. 'text', 'application/json+a2ui'). */
  outputModes?: string[];
  [key: string]: unknown;
}

/**
 * Declared capabilities of an A2A Agent.
 */
export interface AgentCapability {
  /** Indicates whether the agent supports SSE streaming responses. */
  streaming?: boolean;
  /** Indicates whether the agent supports asynchronous push notifications. */
  pushNotifications?: boolean;
  /** Custom protocol extensions supported by the agent. */
  extensions?: Array<{
    uri: string;
    description?: string;
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
}

/**
 * Supported network interface exposed by an A2A Agent (v1.0 specification).
 */
export interface AgentInterface {
  /** Target service endpoint URL for this interface. */
  url: string;
  /** Primary protocol binding (e.g. 'JSONRPC', 'HTTP_JSON', 'GRPC'). */
  protocolBinding?: string;
  /** Legacy protocol transport string (e.g. 'JSONRPC'). */
  transport?: string;
  [key: string]: unknown;
}

/**
 * Specification schema for an AgentCard manifest published by an A2A compliant service.
 * Supports both v0.3 (top-level 'url') and v1.0 ('supportedInterfaces') schemas.
 */
export interface AgentCard {
  /** Target service URL if different from discovery endpoint (v0.3 format). */
  url?: string;
  /** Supported protocol interfaces and endpoints exposed by the agent (v1.0 format). */
  supportedInterfaces?: AgentInterface[];
  /** Protobuf snake_case alias for supportedInterfaces. */
  supported_interfaces?: AgentInterface[];
  /** Preferred transport protocol if specified (v0.3 format). */
  preferredTransport?: string;
  /** Protobuf snake_case alias for preferredTransport. */
  preferred_transport?: string;
  /** Display name of the agent. */
  name: string;
  /** High-level description of the agent's purpose and functionality. */
  description?: string;
  /** Semantic version string of the agent service. */
  version?: string;
  /** URL to the agent's icon or avatar image. */
  iconUrl?: string;
  /** Protobuf snake_case alias for iconUrl. */
  icon_url?: string;
  /** URL to external documentation or home page for the agent. */
  documentationUrl?: string;
  /** Protobuf snake_case alias for documentationUrl. */
  documentation_url?: string;
  /** Declared protocol capabilities of the agent. */
  capabilities?: AgentCapability;
  /** Default input modalities accepted by the agent (e.g. 'text', 'image'). */
  defaultInputModes?: string[];
  /** Protobuf snake_case alias for defaultInputModes. */
  default_input_modes?: string[];
  /** Default output modalities generated by the agent (e.g. 'text', 'application/json+a2ui'). */
  defaultOutputModes?: string[];
  /** Protobuf snake_case alias for defaultOutputModes. */
  default_output_modes?: string[];
  /** Array of discrete skills/tools exposed by the agent. */
  skills?: AgentSkill[];
  /** Suggested starter prompts or queries for interacting with the agent. */
  samplePrompts?: string[];
  /** Protobuf snake_case alias for samplePrompts. */
  sample_prompts?: string[];
}

/**
 * Tool call invocation inside an A2A message turn.
 */
export interface A2aToolCall {
  name: string;
  id?: string;
  args?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Tool result return inside an A2A message turn.
 */
export interface A2aToolResult {
  name?: string;
  id?: string;
  result?: unknown;
  error?: string;
  [key: string]: unknown;
}

/**
 * Artifact payload attached or generated in an A2A task.
 */
export interface A2aArtifact {
  id?: string;
  artifactId?: string;
  name?: string;
  description?: string;
  metadata?: Record<string, unknown>;
  parts?: A2aPart[];
  [key: string]: unknown;
}

/**
 * Single content part of an A2A message turn.
 *
 * Supports both v0.3 and v1.0 part formats:
 * - Text part: { text: string }
 * - File (URI): { url: string, mediaType?: string, filename?: string }
 * - File (raw bytes base64): { raw: string, mediaType?: string, filename?: string }
 * - File (v0.3 nested): { file: { uri?: string, bytes?: string, mimeType?: string, name?: string } }
 * - Data part: { data: object }
 */
export interface A2aPart {
  /** Text content (v0.3 / v1.0). */
  text?: string;
  /** File URI oneof (v1.0 flat format). */
  url?: string;
  /** Raw file bytes encoded as base64 (v1.0 flat format). */
  raw?: string;
  /** MIME/Media type for file or data parts (v1.0 camelCase). */
  mediaType?: string;
  /** Protobuf snake_case alias for mediaType. */
  media_type?: string;
  /** Standard MIME type alias. */
  mimeType?: string;
  /** Filename for attached file parts (v1.0). */
  filename?: string;
  /** Model reasoning or thought content. */
  thought?: string;
  /** Explicit kind discriminator. */
  kind?: string;
  /** File part nested payload (v0.3 format). */
  file?: {
    name?: string;
    mimeType?: string;
    data?: string; // base64 encoded
    bytes?: string;
    uri?: string;
    [key: string]: unknown;
  };
  /** Structured data or A2UI component item payload. */
  data?: Record<string, unknown>;
  /** Discrete tool invocation. */
  toolCall?: A2aToolCall;
  /** Discrete tool execution return. */
  toolResult?: A2aToolResult;
  /** Attached artifact payload. */
  artifact?: A2aArtifact;
  /** Optional metadata associated with the part. */
  metadata?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Message object exchanged within an A2A task session.
 */
export interface A2aMessage {
  role: 'user' | 'agent' | 'assistant' | 'system' | 'ROLE_USER' | 'ROLE_AGENT' | string;
  parts: A2aPart[];
  contextId?: string;
  context_id?: string;
  taskId?: string;
  task_id?: string;
  messageId?: string;
  message_id?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Known A2A v1.0 task states (from protobuf enum mapping).
 */
export enum A2aV1TaskState {
  UNSPECIFIED = 'TASK_STATE_UNSPECIFIED',
  SUBMITTED = 'TASK_STATE_SUBMITTED',
  WORKING = 'TASK_STATE_WORKING',
  COMPLETED = 'TASK_STATE_COMPLETED',
  FAILED = 'TASK_STATE_FAILED',
  CANCELED = 'TASK_STATE_CANCELED',
  CANCELLED = 'TASK_STATE_CANCELLED',
  INPUT_REQUIRED = 'TASK_STATE_INPUT_REQUIRED',
  REJECTED = 'TASK_STATE_REJECTED',
  AUTH_REQUIRED = 'TASK_STATE_AUTH_REQUIRED',
}

/**
 * Known A2A v0.3 task states.
 */
export enum A2aV03TaskState {
  UNKNOWN = 'unknown',
  SUBMITTED = 'submitted',
  WORKING = 'working',
  COMPLETED = 'completed',
  FAILED = 'failed',
  CANCELED = 'canceled',
  CANCELLED = 'cancelled',
  INPUT_REQUIRED = 'input-required',
  REJECTED = 'rejected',
  AUTH_REQUIRED = 'auth-required',
}

/**
 * Known A2A Protobuf integer task state enum values.
 */
export enum A2aProtoTaskState {
  UNSPECIFIED = 0,
  SUBMITTED = 1,
  WORKING = 2,
  COMPLETED = 3,
  FAILED = 4,
  CANCELED = 5,
  INPUT_REQUIRED = 6,
  REJECTED = 7,
  AUTH_REQUIRED = 8,
}

/**
 * Task state lifecycle status token in standard A2A specification.
 * Supports v0.3 lowercase, v1.0 enum names, and Protobuf integer enums.
 */
export type TaskState = A2aV03TaskState | A2aV1TaskState | A2aProtoTaskState | number | string;

/**
 * Mapping from v1.0 protobuf enum names to standardized lowercase display strings.
 */
export const TASK_STATE_DISPLAY: Record<string, string> = {
  TASK_STATE_UNSPECIFIED: 'unspecified',
  TASK_STATE_SUBMITTED: 'submitted',
  TASK_STATE_WORKING: 'working',
  TASK_STATE_COMPLETED: 'completed',
  TASK_STATE_FAILED: 'failed',
  TASK_STATE_CANCELED: 'canceled',
  TASK_STATE_CANCELLED: 'canceled',
  TASK_STATE_INPUT_REQUIRED: 'input-required',
  TASK_STATE_REJECTED: 'rejected',
  TASK_STATE_AUTH_REQUIRED: 'auth-required',
};

/**
 * Mapping from protobuf integer enum values to standardized display strings.
 */
export const TASK_STATE_INT_MAP: Record<number, string> = {
  [A2aProtoTaskState.UNSPECIFIED]: 'unknown',
  [A2aProtoTaskState.SUBMITTED]: 'submitted',
  [A2aProtoTaskState.WORKING]: 'working',
  [A2aProtoTaskState.COMPLETED]: 'completed',
  [A2aProtoTaskState.FAILED]: 'failed',
  [A2aProtoTaskState.CANCELED]: 'canceled',
  [A2aProtoTaskState.INPUT_REQUIRED]: 'input-required',
  [A2aProtoTaskState.REJECTED]: 'rejected',
  [A2aProtoTaskState.AUTH_REQUIRED]: 'auth-required',
};

/**
 * Terminal states that signal an A2A task or stream is completed in Protobuf enum integer representation.
 */
export const TERMINAL_PROTO_TASK_STATES: ReadonlySet<A2aProtoTaskState> = new Set([
  A2aProtoTaskState.COMPLETED,
  A2aProtoTaskState.FAILED,
  A2aProtoTaskState.CANCELED,
  A2aProtoTaskState.REJECTED,
]);

/**
 * Normalizes any TaskState representation (v1.0 enum name, Protobuf integer, or v0.3 lowercase)
 * into a consistent lowercase string for UI display and status checks.
 */
export function normalizeTaskState(state: unknown): string {
  if (state === undefined || state === null) return 'unknown';
  if (typeof state === 'number') {
    return TASK_STATE_INT_MAP[state] || String(state);
  }
  const str = String(state).trim();
  if (!str) return 'unknown';
  const numericVal = Number(str);
  if (!isNaN(numericVal) && numericVal in TASK_STATE_INT_MAP) {
    return TASK_STATE_INT_MAP[numericVal];
  }
  if (TASK_STATE_DISPLAY[str]) {
    return TASK_STATE_DISPLAY[str];
  }
  const upper = str.toUpperCase();
  if (TASK_STATE_DISPLAY[upper]) {
    return TASK_STATE_DISPLAY[upper];
  }
  return str.toLowerCase();
}

/**
 * Terminal states that signal an A2A task or stream is completed.
 */
export const TERMINAL_TASK_STATES: ReadonlySet<string> = new Set([
  'completed',
  'canceled',
  'cancelled',
  'failed',
  'rejected',
  'success',
  'done',
  'task_state_completed',
  'task_state_canceled',
  'task_state_cancelled',
  'task_state_failed',
  'task_state_rejected',
]);

/**
 * Checks whether a given task status, state, or event represents a terminal state.
 *
 * Robustly normalizes Protobuf enum integers, enum strings, and event objects
 * into standardized terminal states without fragile hardcoded numbers.
 */
export function isTerminalTaskState(stateOrEvent: unknown): boolean {
  if (stateOrEvent === undefined || stateOrEvent === null) return false;
  if (typeof stateOrEvent === 'object') {
    const obj = stateOrEvent as Record<string, unknown>;
    if (obj['final'] === true || obj['isCompleted'] === true) {
      return true;
    }
    if ('status' in obj) {
      const rawStatus = obj['status'];
      const rawState =
        typeof rawStatus === 'object' && rawStatus !== null
          ? (rawStatus as Record<string, unknown>)['state']
          : rawStatus;
      return isTerminalTaskState(rawState);
    }
    return false;
  }
  const normalized = normalizeTaskState(stateOrEvent);
  return TERMINAL_TASK_STATES.has(normalized);
}

/**
 * Event stream chunk emitted during A2A streaming execution.
 *
 * Supports both camelCase (v0.3 / TypeScript JSON) and snake_case (v1.0 Protobuf
 * / Python SDKs) field names, as well as Protobuf StreamResponse oneof wrappers
 * (`task`, `status_update`, `artifact_update`).
 */
export interface TaskStatusUpdateEvent {
  kind?: 'task' | 'status-update' | 'artifact-update' | 'message' | string;
  id?: string;
  taskId?: string;
  task_id?: string;
  contextId?: string;
  context_id?: string;
  message?: A2aMessage;
  parts?: A2aPart[];
  status?:
    | {
        state?: TaskState;
        message?: string | A2aMessage;
        [key: string]: unknown;
      }
    | string;
  artifact?: A2aArtifact;
  artifacts?: A2aArtifact[];
  final?: boolean;
  error?: string;
  validation_errors?: string[];
  validationErrors?: string[];
  // Protobuf StreamResponse oneof payload wrappers
  task?: Record<string, unknown>;
  status_update?: Record<string, unknown>;
  statusUpdate?: Record<string, unknown>;
  artifact_update?: Record<string, unknown>;
  artifactUpdate?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Options passed to A2A transport calls.
 */
export interface A2aTransportOptions {
  contextId?: string;
  taskId?: string;
  tenantId?: string;
  headers?: Record<string, string>;
  abortSignal?: AbortSignal;
}

/**
 * Transport contract interface for A2A communication.
 */
export interface A2aTransport {
  /**
   * Retrieves the AgentCard from the target endpoint.
   */
  getAgentCard(baseUrl: string, options?: A2aTransportOptions): Promise<AgentCard>;

  /**
   * Streams conversational message turns and task updates from the target endpoint.
   */
  sendMessageStream(
    baseUrl: string,
    message: A2aMessage,
    options?: A2aTransportOptions,
  ): AsyncIterable<TaskStatusUpdateEvent>;

  /**
   * Dispatches interactive user action payload back to the target agent task.
   */
  sendActionStream(
    baseUrl: string,
    taskId: string,
    action: unknown,
    options?: A2aTransportOptions,
  ): AsyncIterable<TaskStatusUpdateEvent>;
}
