/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * A discrete skill, tool, or capability exposed by an A2A Agent.
 */
export interface AgentSkill {
  /** Unique skill identifier. */
  id: string;
  /** Human-readable skill name. */
  name: string;
  /** Description of what this skill does. */
  description?: string;
  /** Specific input modalities accepted by this skill (e.g. 'text', 'audio', 'image'). */
  inputModes?: string[];
  /** Specific output modalities produced by this skill (e.g. 'text', 'application/json+a2ui'). */
  outputModes?: string[];
  [key: string]: unknown;
}

/**
 * Declared capabilities of an A2A Agent.
 */
export interface AgentCapability {
  /** Indicates whether the agent supports SSE streaming responses. */
  streaming?: boolean;
  /** Indicates whether the agent supports asynchronous push notifications. */
  pushNotifications?: boolean;
  /** Custom protocol extensions supported by the agent. */
  extensions?: Array<{
    uri: string;
    description?: string;
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
}

/**
 * Specification schema for an AgentCard manifest published by an A2A compliant service.
 */
export interface AgentCard {
  /** Target service URL if different from discovery endpoint. */
  url?: string;
  /** Preferred transport protocol if specified. */
  preferredTransport?: string;
  /** Display name of the agent. */
  name: string;
  /** High-level description of the agent's purpose and functionality. */
  description?: string;
  /** Semantic version string of the agent service. */
  version?: string;
  /** URL to the agent's icon or avatar image. */
  iconUrl?: string;
  /** URL to external documentation or home page for the agent. */
  documentationUrl?: string;
  /** Declared protocol capabilities of the agent. */
  capabilities?: AgentCapability;
  /** Default input modalities accepted by the agent (e.g. 'text', 'image'). */
  defaultInputModes?: string[];
  /** Default output modalities generated by the agent (e.g. 'text', 'application/json+a2ui'). */
  defaultOutputModes?: string[];
  /** Array of discrete skills/tools exposed by the agent. */
  skills?: AgentSkill[];
  /** Suggested starter prompts or queries for interacting with the agent. */
  samplePrompts?: string[];
}

/**
 * Tool call invocation inside an A2A message turn.
 */
export interface A2aToolCall {
  name: string;
  id?: string;
  args?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Tool result return inside an A2A message turn.
 */
export interface A2aToolResult {
  name?: string;
  id?: string;
  result?: unknown;
  error?: string;
  [key: string]: unknown;
}

/**
 * Artifact payload attached or generated in an A2A task.
 */
export interface A2aArtifact {
  id?: string;
  name?: string;
  parts?: A2aPart[];
  [key: string]: unknown;
}

/**
 * Single content part of an A2A message turn.
 */
export interface A2aPart {
  text?: string;
  file?: {
    name?: string;
    mimeType?: string;
    data?: string; // base64 encoded
    uri?: string;
    [key: string]: unknown;
  };
  data?: Record<string, unknown>;
  toolCall?: A2aToolCall;
  toolResult?: A2aToolResult;
  artifact?: A2aArtifact;
  metadata?: Record<string, unknown>;
  [key: string]: unknown;
}

/**
 * Message object exchanged within an A2A task session.
 */
export interface A2aMessage {
  role: 'user' | 'agent' | 'assistant' | 'system';
  parts: A2aPart[];
  contextId?: string;
  taskId?: string;
  messageId?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Task state lifecycle status token in standard A2A specification.
 */
export type TaskState =
  | 'submitted'
  | 'working'
  | 'input-required'
  | 'completed'
  | 'canceled'
  | 'failed'
  | 'rejected'
  | 'auth-required'
  | 'unknown';

/**
 * Terminal states that signal an A2A task or stream is completed.
 */
export const TERMINAL_TASK_STATES: ReadonlySet<string> = new Set([
  'completed',
  'canceled',
  'cancelled',
  'failed',
  'rejected',
  'success',
  'done',
]);

/**
 * Event stream chunk emitted during A2A streaming execution.
 */
export interface TaskStatusUpdateEvent {
  taskId?: string;
  contextId?: string;
  message?: A2aMessage;
  status?:
    | {
        state?: TaskState | string;
        message?: string | A2aMessage;
        [key: string]: unknown;
      }
    | string;
  artifact?: A2aArtifact;
  final?: boolean;
}

/**
 * Options passed to A2A transport calls.
 */
export interface A2aTransportOptions {
  contextId?: string;
  taskId?: string;
  tenantId?: string;
  headers?: Record<string, string>;
  abortSignal?: AbortSignal;
}

/**
 * Transport contract interface for A2A communication.
 */
export interface A2aTransport {
  /**
   * Retrieves the AgentCard from the target endpoint.
   */
  getAgentCard(baseUrl: string, options?: A2aTransportOptions): Promise<AgentCard>;

  /**
   * Streams conversational message turns and task updates from the target endpoint.
   */
  sendMessageStream(
    baseUrl: string,
    message: A2aMessage,
    options?: A2aTransportOptions,
  ): AsyncIterable<TaskStatusUpdateEvent>;

  /**
   * Dispatches interactive user action payload back to the target agent task.
   */
  sendActionStream(
    baseUrl: string,
    taskId: string,
    action: unknown,
    options?: A2aTransportOptions,
  ): AsyncIterable<TaskStatusUpdateEvent>;
}
